# Generated by Django 5.2.17 on 2026-09-09 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the category (required).', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug. Auto-generated if left blank.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug for post identification. Auto-generated from title.', max_length=250, unique=True)),
                ('content', models.TextField(help_text='Main content body of the post.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last modified.')),
                ('is_published', models.BooleanField(default=False, help_text='Designates whether this post is published and visible publicly.')),
                ('author', models.ForeignKey(help_text='The author of this post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='The category this post belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
